Vagrant.configure("2") do |config|
    config.vm.define "database" do |db|
        db.vm.box = "ubuntu/focal64"
        db.vm.hostname = "db01"
        db.vm.network "private_network", ip: "192.168.100.2"
        db.vm.network "forwarded_port", guest: 3306, host: 33066
        db.vm.provision "shell", path: "db_config.sh"
        db.vm.provider "virtualbox" do |vb|
            vb.memory = "1024"           
        end
    end
    config.vm.define "web" do |web|
        web.vm.box = "ubuntu/focal64"
        web.vm.hostname = "web01"
        web.vm.network "private_network", ip: "192.168.100.3"
        web.vm.network "forwarded_port", guest: 80, host: 8080
        web.vm.syncedfolders ".", "/var/www/html"
        web.vm.provison "shell", path: "web_config.sh"
        web.vm.provider "virtualbox" do |vb|
            vb.memory = "2048"       
        end
    end
end